apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Example ACL rules for consuming from my-topic using consumer group my-group
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: All
        host: "*"
      # Example ACL rules for producing to topic my-topic
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: All
        host: "*"